excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://EconomiCurtis.github.io/pctblog
title: Curtis' PCT Blog
email: CurtisKephart@gmail.com
author: Curtis
description: My Blog of PCT What-not
paginate: 30
google_analytics: 
