excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://EconomiCurtis.github.io
title: Curtis
email: Curtisesjunk@gmail.com
author: Curtis
description: My awesome new site
paginate: 15
google_analytics: 
